### ISSUE TITLE
document $not

### ISSUE THREAD

**Issue by ahdinosaur** [dominictarr/map-filter-reduce#4]
i wanted to a query to find all root messages (messages without a `content.root` key).

i had to look through Patchwork, Patchtron, and then finally Patchbay code until i [found a hint](https://github.com/ssbc/patchbay/blob/e722641cbffa14a6c07ea99bba8dccb1a15c78c1/app/page/posts.js#L334-L369).

is it possible to document `$not`? i'm not even sure what exactly it does, but `$not: true` worked for my use case of searching for an undefined value.

**Comment by dominictarr** [comment]
fixed in 3.2.2!

I also use `{$is: 'undefined'}` for that, but `{$not: true}` is better.

**Comment by dominictarr** [comment]
also to see exactly what an operator does, you won't have any trouble with the source: https://github.com/dominictarr/map-filter-reduce/blob/master/simple/maps.js and reduces are here: https://github.com/dominictarr/map-filter-reduce/blob/master/simple/reduces.js

unfortunately the main methods $filter, $map, $reduce are not so easy to understand.
